import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { logger } from '../../utils/logger.js';
import type { SiteMap } from '../../types/index.js';

export interface ThemeOptions {
  styleMode: 'faithful' | 'native';
  siteName: string;
}

export class ThemeService {
  async generate(outputDir: string, siteMap: SiteMap, options: ThemeOptions): Promise<string> {
    logger.info('Generating Twenty Twenty-Five child theme', { mode: options.styleMode });

    const themeDir = join(outputDir, 'theme', 'twentytwentyfive-child');

    await mkdir(themeDir, { recursive: true });

    // Generate style.css
    await this.generateStyleCSS(themeDir, options);

    // Generate functions.php
    await this.generateFunctionsPHP(themeDir);

    // Generate templates
    await this.generateTemplates(themeDir, siteMap, options);

    // Generate theme.json for block settings
    await this.generateThemeJSON(themeDir, options);

    logger.info(`Child theme generated at: ${themeDir}`);

    return themeDir;
  }

  private async generateStyleCSS(themeDir: string, options: ThemeOptions): Promise<void> {
    const content = `/*
 Theme Name:   Twenty Twenty-Five Child
 Theme URI:    https://example.com
 Description:  Child theme for ${options.siteName} - Generated by HTML2WP
 Author:       HTML2WP
 Author URI:   https://example.com
 Template:     twentytwentyfive
 Version:      1.0.0
 License:      GNU General Public License v2 or later
 License URI:  http://www.gnu.org/licenses/gpl-2.0.html
 Text Domain:  twentytwentyfive-child
*/

/* ${options.styleMode === 'faithful' ? 'Faithful mode: Original site styles preserved below' : 'Native mode: Using Twenty Twenty-Five defaults' } */
`;

    await writeFile(join(themeDir, 'style.css'), content);
  }

  private async generateFunctionsPHP(themeDir: string): Promise<void> {
    const content = `<?php
/**
 * Twenty Twenty-Five Child Theme functions
 */

function twentytwentyfive_child_enqueue_styles() {
    wp_enqueue_style(
        'parent-style',
        get_template_directory_uri() . '/style.css',
        array(),
        '1.0.0'
    );
    wp_enqueue_style(
        'child-style',
        get_stylesheet_uri(),
        array('parent-style'),
        '1.0.0'
    );
}
add_action('wp_enqueue_scripts', 'twentytwentyfive_child_enqueue_styles');
`;

    await writeFile(join(themeDir, 'functions.php'), content);
  }

  private async generateTemplates(themeDir: string, siteMap: SiteMap, options: ThemeOptions): Promise<void> {
    const templatesDir = join(themeDir, 'templates');
    await mkdir(templatesDir, { recursive: true });

    // Generate page template
    const pageTemplate = `<!-- wp:template {"title":"Page Template"} -->
${options.styleMode === 'faithful' ? '<!-- wp:group {"layout":{"type":"constrained"}} -->' : ''}
<!-- wp:group {"tagName":"main","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"default"}} -->
<main class="wp-block-group">
  <!-- wp:group {"layout":{"type":"constrained"}} -->
  <div class="wp-block-group">
    <!-- wp:post-title {"level":1} /-->
    <!-- wp:post-content {"layout":{"type":"constrained"}} /-->
  </div>
</main>
<!-- /wp:group -->
${options.styleMode === 'faithful' ? '<!-- /wp:group -->' : ''}
<!-- /wp:template -->
`;

    await writeFile(join(templatesDir, 'page.html'), pageTemplate);

    // Generate index template for posts
    const indexTemplate = `<!-- wp:template {"title":"Index Template"} -->
<!-- wp:group {"tagName":"main","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"default"}} -->
<main class="wp-block-group">
  <!-- wp:group {"layout":{"type":"constrained"}} -->
  <div class="wp-block-group">
    <!-- wp:query {"query":{"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true}} -->
    <div class="wp-block-query">
      <!-- wp:post-template -->
        <!-- wp:post-title {"isLink":true} /-->
        <!-- wp:post-date /-->
        <!-- wp:post-excerpt /-->
      <!-- /wp:post-template -->
      <!-- wp:query-pagination -->
        <!-- wp:query-pagination-previous /-->
        <!-- wp:query-pagination-numbers /-->
        <!-- wp:query-pagination-next /-->
      <!-- /wp:query-pagination -->
    </div>
    <!-- /wp:query -->
  </div>
</main>
<!-- /wp:group -->
<!-- /wp:template -->
`;

    await writeFile(join(templatesDir, 'index.html'), indexTemplate);
  }

  private async generateThemeJSON(themeDir: string, options: ThemeOptions): Promise<void> {
    const themeJSON = {
      version: '1.0',
      title: 'Twenty Twenty-Five Child',
      templateParts: [
        {
          name: 'header',
          area: 'header',
          title: 'Header'
        },
        {
          name: 'footer',
          area: 'footer',
          title: 'Footer'
        }
      ],
      styles: options.styleMode === 'faithful'
        ? {
            color: {
              palette: [
                { slug: 'primary', color: '#0073aa', name: 'Primary' },
                { slug: 'secondary', color: '#23282d', name: 'Secondary' }
              ]
            },
            typography: {
              fontFamilies: [
                {
                  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
                  slug: 'system',
                  name: 'System Font'
                }
              ]
            }
          }
        : {}
    };

    await writeFile(join(themeDir, 'theme.json'), JSON.stringify(themeJSON, null, 2));
  }
}
